block.o: block.c
	$(CC) ${CFLAGS} -c block.c -o block.o ${INCLUDES}

queries_state.o:
	$(CC) ${CFLAGS} -c queries_state.c -o queries_state.o ${INCLUDES}


clean:
	rm -f block.o queries_state.o

all: block.o