# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  compile-and-test:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: circleci/buildpack-deps:bullseye-browsers-legacy
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Install deps"
          command: "sudo apt install -y cmake googletest libgtest-dev"
      - run:
          name: "CMakeFiles"
          command: "cmake ."
      - run:
          name: "Compile"
          command: "make -j"
      - run:
          name: "Test"
          command: "ctest . -j $(nproc)"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  compile-and-test-workflow:
    jobs:
      - compile-and-test
